# Task 2: Medical dataset

In [1]:
%load_ext autoreload
%autoreload 2

import numpy as np
import pandas as pd

from sklearn.linear_model import LogisticRegression, Ridge, HuberRegressor, SGDClassifier
from sklearn.svm import SVC, LinearSVC
from sklearn.kernel_approximation import RBFSampler, Nystroem
from sklearn.pipeline import Pipeline
import sklearn.metrics as metrics

import utils
import time

pd.options.display.max_columns = 40

---
## 0. Preliminary Analysis

In [22]:
feat_test = pd.read_csv("./train_features_filled.zip", header=None, index_col=0)
feat_test

1     2     3     4     5     6     7     8     9     10    11    12   \
0                                                                               
1       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
10      NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
100     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
1000   26.0  26.0  29.5  30.0  32.5  35.5  37.0  37.0  35.5  30.0  28.5  29.0   
10000   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
...     ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   
9993    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
9995    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
9996    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
9998    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
9999    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   

        13    14         15         16    17         18         19    20   \
0                                                                           
1       NaN   NaN        NaN        NaN   NaN        NaN        NaN   NaN   
10     27.8  27.8  27.800000  27.800000  27.8  27.800000  27.800000  27.8   
100    20.9  20.9  20.900000  20.900000  20.9  20.900000  20.900000  20.9   
1000    NaN   NaN        NaN        NaN   NaN        NaN        NaN   NaN   
10000  25.7  25.7  26.333333  26.966667  27.6  28.233333  28.866667  29.5   
...     ...   ...        ...        ...   ...        ...        ...   ...   
9993    NaN   NaN        NaN        NaN   NaN        NaN        NaN   NaN   
9995   55.5  55.5  55.500000  55.500000  55.5  55.500000  55.500000  55.5   
9996    NaN   NaN        NaN        NaN   NaN        NaN        NaN   NaN   
9998   34.7  34.7  34.700000  34.700000  34.7  34.700000  34.700000  34.7   
9999   36.4  36.4  36.400000  36.400000  36.4  36.400000  36.400000  36.4   

       ...    390    391    392    393    394    395    396   397    398  \
0      ...                                                                 
1      ...  106.0  112.0  121.0  118.0  110.0  124.0  102.0  7.33  7.330   
10     ...  123.0  113.0  114.0  136.0  140.0  131.0  136.0   NaN    NaN   
100    ...  113.0  130.0  113.0  113.0  110.0   97.0  116.0   NaN    NaN   
1000   ...  144.0  175.0  185.0  152.0  152.0  134.0  125.0  7.30  7.300   
10000  ...  130.0  132.0   98.0  111.0  152.0  141.0  132.0  7.35  7.350   
...    ...    ...    ...    ...    ...    ...    ...    ...   ...    ...   
9993   ...   90.0   92.0   92.0   95.0   96.0  101.0  101.0   NaN    NaN   
9995   ...  183.0  184.0  181.0  187.0  187.0  197.0  174.0   NaN    NaN   
9996   ...  106.0   88.0   80.0   96.0  100.0  100.0   95.0  7.41  7.385   
9998   ...  146.0  119.0  123.0  142.0  143.0  126.0  156.0   NaN    NaN   
9999   ...  109.0   90.0  110.0  123.0  138.0  125.0  128.0   NaN    NaN   

         399       400       401    402       403       404    405   406  \
0                                                                          
1      7.370  7.370000  7.410000  7.406  7.402000  7.398000  7.394  7.39   
10       NaN       NaN       NaN    NaN       NaN       NaN    NaN   NaN   
100      NaN       NaN       NaN    NaN       NaN       NaN    NaN   NaN   
1000   7.300  7.300000  7.300000  7.300  7.300000  7.300000  7.300  7.30   
10000  7.385  7.420000  7.390000  7.400  7.400000  7.400000  7.400  7.40   
...      ...       ...       ...    ...       ...       ...    ...   ...   
9993     NaN       NaN       NaN    NaN       NaN       NaN    NaN   NaN   
9995     NaN       NaN       NaN    NaN       NaN       NaN    NaN   NaN   
9996   7.360  7.376667  7.393333  7.410  7.416667  7.423333  7.430  7.43   
9998     NaN       NaN       NaN    NaN       NaN       NaN    NaN   NaN   
9999     NaN       NaN       NaN    NaN       NaN  

In [4]:
feat_train = pd.read_csv("./train_features.csv")
labl_train = pd.read_csv("./train_labels.csv")
feat_test = pd.read_csv("./test_features.csv")

In [97]:
utils.get_score("./train_labels.csv", "./recall_train.zip")

[0.880140104158019, 0.7682702066333779, 0.7163509452862231, 0.7200754850470517, 0.7163416600616637, 0.7564771589791436, 0.7676717431220972, 0.8042015344518387, 0.7284277753577496, 0.9077601581932911]
[0.6519184425430589, 0.7291738267644755, 0.5417486006038639, 0.7896502307334095]
0.7765716771290455 0.6566563580952569 0.6781227751612019


0.7037836034618348

In [5]:
feat_train_reformed = utils.patient_feat_flatten(feat_train)
feat_test_reformed = utils.patient_feat_flatten(feat_test)

In [ ]:
feat_train_filled = utils.fill_interp(feat_train_reformed)
# feat_train_filled = pd.read_csv("./intermediate.zip", header=None, names=feat_train_reformed.columns)

In [237]:
feat_train_filled.to_csv("./intermediate.zip", header=False, compression="zip")

In [238]:
feat_train_fill0 = feat_train_filled.fillna(0.0, inplace=False)

---
## 1. Training

In [6]:
feat_train_filled = pd.read_csv("./train_features_filled.zip", header=None, names=feat_train_reformed.columns)
feat_train_filled = feat_train_filled.groupby(axis=1, level=0).apply(lambda df: df / np.nanmedian(df.to_numpy().flatten()))
feat_train_fill0 = feat_train_filled.fillna(0.0, inplace=False)

In [9]:
feat_train_filled

EtCO2                                                              \
             0         1         2         3         4         5         6    
1           NaN       NaN       NaN       NaN       NaN       NaN       NaN   
10          NaN       NaN       NaN       NaN       NaN       NaN       NaN   
100         NaN       NaN       NaN       NaN       NaN       NaN       NaN   
1000   0.787879  0.787879  0.893939  0.909091  0.984848  1.075758  1.121212   
10000       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
...         ...       ...       ...       ...       ...       ...       ...   
9993        NaN       NaN       NaN       NaN       NaN       NaN       NaN   
9995        NaN       NaN       NaN       NaN       NaN       NaN       NaN   
9996        NaN       NaN       NaN       NaN       NaN       NaN       NaN   
9998        NaN       NaN       NaN       NaN       NaN       NaN       NaN   
9999        NaN       NaN       NaN       NaN       NaN       NaN       NaN   

                                                              PTT            \
             7         8         9         10        11        0         1    
1           NaN       NaN       NaN       NaN       NaN       NaN       NaN   
10          NaN       NaN       NaN       NaN       NaN  0.879747  0.879747   
100         NaN       NaN       NaN       NaN       NaN  0.661392  0.661392   
1000   1.121212  1.075758  0.909091  0.863636  0.878788       NaN       NaN   
10000       NaN       NaN       NaN       NaN       NaN  0.813291  0.813291   
...         ...       ...       ...       ...       ...       ...       ...   
9993        NaN       NaN       NaN       NaN       NaN       NaN       NaN   
9995        NaN       NaN       NaN       NaN       NaN  1.756329  1.756329   
9996        NaN       NaN       NaN       NaN       NaN       NaN       NaN   
9998        NaN       NaN       NaN       NaN       NaN  1.098101  1.098101   
9999        NaN       NaN       NaN       NaN       NaN  1.151899  1.151899   

                                                                   ...  \
             2         3         4         5         6         7   ...   
1           NaN       NaN       NaN       NaN       NaN       NaN  ...   
10     0.879747  0.879747  0.879747  0.879747  0.879747  0.879747  ...   
100    0.661392  0.661392  0.661392  0.661392  0.661392  0.661392  ...   
1000        NaN       NaN       NaN       NaN       NaN       NaN  ...   
10000  0.833333  0.853376  0.873418  0.893460  0.913502  0.933544  ...   
...         ...       ...       ...       ...       ...       ...  ...   
9993        NaN       NaN       NaN       NaN       NaN       NaN  ...   
9995   1.756329  1.756329  1.756329  1.756329  1.756329  1.756329  ...   
9996        NaN       NaN       NaN       NaN       NaN       NaN  ...   
9998   1.098101  1.098101  1.098101  1.098101  1.098101  1.098101  ...   
9999   1.151899  1.151899  1.151899  1.151899  1.151899  1.151899  ...   

           ABPs                                                              \
             5         6         7         8         9         10        11   
1      0.883333  0.933333  1.008333  0.983333  0.916667  1.033333  0.850000   
10     1.025000  0.941667  0.950000  1.133333  1.166667  1.091667  1.133333   
100    0.941667  1.083333  0.941667  0.941667  0.916667  0.808333  0.966667   
1000   1.200000  1.458333  1.541667  1.266667  1.266667  1.116667  1.041667   
10000  1.083333  1.100000  0.816667  0.925000  1.266667  1.175000  1.100000   
...         ...       ...       ...       ...       ...       ...       ...   
9993   0.750000  0.766667  0.766667  0.791667  0.800000  0.841667  0.841667   
9995   1.525000  1.533333  1.508333  1.558333  1.558333  1.641667  1.450000   
9996   0.883333  0.733333  0.666667  0.800000  0.833333  0.833333  0.791667   
9998   1.216667  0.991667  1.025000  1.183333  1.191667  1.050000  1.300000   
9999   0.908333  0.750000  0.916667  1.0250

In [341]:
feat_train_mat = np.concatenate((feat_train_fill0.to_numpy(), np.ones((feat_train_reformed.shape[0], 1))), axis=1)

In [424]:
rbf_kernel = RBFSampler(gamma=2, n_components=10000, random_state=1)
X_rbf_feat = rbf_kernel.fit_transform(feat_train_mat)

In [425]:
X_rbf_feat

array([[ 0.00124752, -0.00560517, -0.01202498, ..., -0.00682438,
         0.00972497, -0.00853319],
       [-0.01294071,  0.01386927,  0.01289027, ...,  0.0123179 ,
         0.0019333 , -0.01055929],
       [-0.0102816 ,  0.00391926, -0.00992195, ..., -0.01391045,
         0.00951419, -0.01131782],
       ...,
       [-0.00202312,  0.00287168,  0.00664406, ...,  0.01040662,
         0.00135352, -0.00219292],
       [-0.01303557, -0.00146097, -0.00506871, ...,  0.01258362,
        -0.00579549, -0.01278685],
       [-0.00729411, -0.00982529, -0.01187047, ...,  0.01411375,
        -0.01183319, -0.00734779]])

In [434]:
rbf_kernel.transform(feat_test_mat)

array([[ 0.01158714, -0.01357454,  0.00763057, ..., -0.00773793,
         0.00022349, -0.00511733],
       [ 0.01413437,  0.01396206,  0.00843097, ...,  0.01198258,
         0.01410292, -0.00505409],
       [-0.01108782, -0.00990463,  0.01413618, ...,  0.01410968,
         0.01140916,  0.01239361],
       ...,
       [ 0.00422473,  0.0122155 ,  0.01070024, ..., -0.00549259,
         0.00658475,  0.01164897],
       [-0.00915065, -0.00669379,  0.01282676, ...,  0.00559994,
         0.0096538 ,  0.01343743],
       [ 0.00738116, -0.00975196,  0.01136088, ..., -0.00343837,
         0.01059531,  0.01412997]])

### Logistic regression

In [383]:
tstart = time.time()

# logit_lin = LogisticRegression(C=1, fit_intercept=False, solver="sag", max_iter=1000).fit(feat_train_mat, labl_train.iloc[:, 1])
logit_lin = SGDClassifier(loss="log", fit_intercept=False, max_iter=100, alpha=1, tol=1e-7).fit(feat_train_mat, labl_train.iloc[:, 11])

tend_lin = time.time()
print("Linear classifier training time: {}".format(tend_lin - tstart))

# logit_nonlin = LogisticRegression(C=1, fit_intercept=False, solver="sag", max_iter=500).fit(X_rbf_feat, labl_train.iloc[:, 11])
logit_nonlin = SGDClassifier(loss="log", fit_intercept=False, max_iter=500, tol=1e-7).fit(X_rbf_feat, labl_train.iloc[:, 11])

tend_nonlin = time.time()
print("Nonlinear kernels training time: {}".format(tend_nonlin - tstart))

Linear classifier training time: 0.9513750076293945
Nonlinear kernels training time: 193.39767217636108


In [384]:
prob_lin = logit_lin.predict_proba(feat_train_mat)[:, 1]
prob_nonlin = logit_nonlin.predict_proba(X_rbf_feat)[:, 1]
prob_lin, prob_nonlin

(array([0.09374422, 0.05322627, 0.05382918, ..., 0.07817172, 0.05483041,
        0.05807976]),
 array([0.45822555, 0.56198689, 0.42468296, ..., 0.47526155, 0.45917428,
        0.4713796 ]))

In [386]:
metrics.roc_auc_score(labl_train.iloc[:, 11], prob_lin), metrics.roc_auc_score(labl_train.iloc[:, 11], prob_nonlin)

(0.5178642040247159, 0.8580173933788627)

### Support-Vector-Machine classification

In [363]:
svm_lin = LinearSVC(fit_intercept=False).fit(feat_train_mat, labl_train.iloc[:, 11])
svm_nonlin = LinearSVC(fit_intercept=False).fit(X_rbf_feat, labl_train.iloc[:, 11])

E:\Miniconda3\envs\intro-ml\lib\site-packages\sklearn\svm\_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,


In [364]:
func_lin = svm_lin.decision_function(feat_train_mat)
prob_svm_lin = 1/(1 + np.exp(-func_lin))

In [367]:
metrics.roc_auc_score(labl_train.iloc[:, 11], prob_svm_lin)

0.6381671930792757

In [52]:
vital_predictor = Lasso(alpha=1, fit_intercept=True).fit(feat_na_filled, labl_train["LABEL_RRate"])

In [53]:
0.5 + 0.5*np.maximum(0, metrics.r2_score(labl_train["LABEL_RRate"], vital_predictor.predict(feat_na_filled)))

0.636415255250034

In [ ]:
logistic_rbf = Pipeline([("rbf_approx", RBFSampler(gamma=2, n_components=1, random_state=1)), 
                         ("sgd_log", SGDClassifier(loss="log", fit_intercept=False, max_iter=500))])
logistic_rbf.fit(

---

## Checking Results

In [451]:
X_rbf_feat[1,:] @ X_rbf_feat[1,:]

0.9918226790121505

In [426]:
feat_test_mat = np.concatenate((feat_test_fill0.to_numpy(), np.ones((feat_test_reformed.shape[0], 1))), axis=1)
X_rbf_feat_test = rbf_kernel.transform(feat_test_mat)

prob_test = logit_nonlin.predict_proba(X_rbf_feat_test)[:, 1]
prob_sorted = prob_test[feat_test_fill0.index.argsort()]
result_prev["LABEL_Sepsis"] = prob_sorted

In [423]:
result_prev.to_csv("./recall_test_rbf.zip", compression="zip", index=False, float_format='%.3f')

In [404]:
utils.get_score("./train_labels.csv", "./recall_train_rbf.zip")

[0.880140104158019, 0.7682702066333779, 0.7163509452862231, 0.7200754850470517, 0.7163416600616637, 0.7564771589791436, 0.7676717431220972, 0.8042015344518387, 0.7284277753577496, 0.9077601581932911]
[0.6519184425430589, 0.7291738267644755, 0.5417486006038639, 0.7896502307334095]
0.7765716771290455 0.8580173933788627 0.6781227751612019


0.77090394855637

In [435]:
X_rbf_feat_test

array([[ 0.01158714, -0.01357454,  0.00763057, ..., -0.00773793,
         0.00022349, -0.00511733],
       [ 0.01413437,  0.01396206,  0.00843097, ...,  0.01198258,
         0.01410292, -0.00505409],
       [-0.01108782, -0.00990463,  0.01413618, ...,  0.01410968,
         0.01140916,  0.01239361],
       ...,
       [ 0.00422473,  0.0122155 ,  0.01070024, ..., -0.00549259,
         0.00658475,  0.01164897],
       [-0.00915065, -0.00669379,  0.01282676, ...,  0.00559994,
         0.0096538 ,  0.01343743],
       [ 0.00738116, -0.00975196,  0.01136088, ..., -0.00343837,
         0.01059531,  0.01412997]])